### ISSUE TITLE
Error load dati in Competenze Personali

### ISSUE THREAD

**Issue by AngeloDotNet** [AngeloDotNet/Blazor.PersonalWebSites#1]
Error:

```
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: net_http_message_not_success_statuscode, 502, Bad Gateway
System.Net.Http.HttpRequestException: net_http_message_not_success_statuscode, 502, Bad Gateway
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.Json.HttpClientJsonExtensions.<GetFromJsonAsyncCore>d__9`1[[System.Collections.Generic.List`1[[Blazor.PersonalWebSites.Models.Models.ViewModels.SkillPersonale, Blazor.PersonalWebSites.Models, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at Blazor.PersonalWebSites.Client.Pages.CompetenzePersonali.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

**Comment by AngeloDotNet** [comment]
Issues resolved with commit 9baa466144aca025402ef76fda90456c30c667d6
